# frozen_string_literal: true

module Report
  # Generates a PDF for cases requiring manual review
  # (when no abuse contacts could be found)
  class GeneratePdfJob < ApplicationJob
    queue_as QUEUE_MAINTENANCE

    def perform(case_id)
      report_case = Report::Case.find_by(id: case_id)

      unless report_case
        Rails.logger.warn("[Report::GeneratePdfJob] Case not found: #{case_id}")
        return
      end

      unless report_case.requires_manual_review?
        Rails.logger.info("[Report::GeneratePdfJob] Case #{report_case.case_number} does not require manual review")
        return
      end

      Rails.logger.info("[Report::GeneratePdfJob] Generating PDF for case #{report_case.case_number}")

      # Generate PDF content (simple text-based for now)
      pdf_content = generate_pdf_content(report_case)

      # Attach to case using Active Storage
      report_case.manual_review_pdf.attach(
        io: StringIO.new(pdf_content),
        filename: "#{report_case.case_number}-manual-review.txt", # Use .txt for now
        content_type: "text/plain"
      )

      # Send notification to ops team
      Report::OpsMailer.with(case: report_case).manual_review_needed.deliver_later

      Rails.logger.info("[Report::GeneratePdfJob] PDF generated and attached for case #{report_case.case_number}")
    end

    private

    def generate_pdf_content(report_case)
      <<~CONTENT
        PHISH.DIRECTORY - MANUAL REVIEW REQUIRED
        =========================================

        Case Number: #{report_case.case_number}
        Created: #{report_case.created_at.strftime('%Y-%m-%d %H:%M:%S UTC')}

        DOMAIN INFORMATION
        ------------------
        Domain: #{report_case.domain_name}
        #{report_case.url_value ? "URL: #{report_case.url_value}" : ""}

        DETECTION DETAILS
        -----------------
        Classification: #{report_case.verdict_snapshot&.classification}
        Confidence: #{(report_case.confidence_at_creation * 100).round(1)}%
        Detection Sources: #{report_case.verdict_snapshot&.sources&.map { |s| s['service'] }&.join(', ')}

        DOMAIN INFO (WHOIS/RDAP)
        ------------------------
        #{format_domain_info(report_case.domain_info)}

        REASON FOR MANUAL REVIEW
        ------------------------
        No abuse contacts could be automatically identified for this domain.
        Please investigate and add appropriate abuse contacts to the database.

        Notes: #{report_case.notes}

        =========================================
        Generated by phish.directory
      CONTENT
    end

    def format_domain_info(domain_info)
      return "No domain info available" if domain_info.blank?

      domain_info.map { |k, v| "#{k.to_s.humanize}: #{v}" }.join("\n")
    end
  end
end
